apiVersion: v1
kind: Service
metadata:
  name: shopservice
  labels:
    app: shopservice
    service: shopservice
spec:
  ports:
    - port: 8089
  selector:
    app: shopservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopservice-v1
  labels:
    app: shopservice
    version: v1
spec:
  selector:
    matchLabels:
      app: shopservice
      version: v1
  template:
    metadata:
      labels:
        app: shopservice
        version: v1
    spec:
      containers:
      - image: <DockerHubAccount>/shop-service:version1
        name: shop-service-container
        ports:
        - containerPort: 8089
